version: '3.1'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
        -  2181:2181
    sqlserver:
        image: liaisonintl/mssql-server-linux
        ports:
        -  1433:1433
        environment:
        -  ACCEPT_EULA=Y
        -  MSSQL_PID=Standard
        -  SA_PASSWORD=1010
        -  MSSQL_AGENT_ENABLED=true
    kafka:
        image: confluentinc/cp-kafka
        depends_on:
        -  zookeeper
        -  sqlserver
        ports:
        -  9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
            KAFKA_BROKER_ID: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1
    connect:
        image: debezium/connect:latest
        ports:
        -  8083:8083
        environment:
            GROUP_ID: 1
            CONFIG_STORAGE_TOPIC: my_connect_configs
            OFFSET_STORAGE_TOPIC: my_connect_offsets
            BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
        -  zookeeper
        -  sqlserver
        -  kafka
